### ISSUE TITLE
Actividad 1 Infografia de gestion de proyectos

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Abraham890#2]
![Abraham_Reyes_Ortiz_Infofrafia_Gestion_6US](https://user-images.githubusercontent.com/79929244/186514488-d2a865d4-38e9-4613-aadf-1eff378d764a.png)

**Comment by bg55-a** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
